### ISSUE TITLE
Does not work in ractive 0.7

### ISSUE THREAD

**Issue by petterek** [ractivejs/Ractive-decorators-sortable#19]
Error message
Uncaught TypeError: sourceKeypath.lastIndexOf is not a functiondragstartHandler @ Sortable.js:72

**Comment by guilhermeaiolfi** [comment]
Yeah. I can confirm that. I'm trying to solve it right now. If I can find a solution I'll get back here.

**Comment by Crisfole** [comment]
+1 Fix worked for m.e

**Comment by petterek** [comment]
+1 Worked here as well
